@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Участник организации: as member 
:Администратор организации: as adminOrg
adminOrg -l-> member

package "Управление группами пользователей" {
    (управление группами пользователей) as userGroupManaging
    adminOrg -- userGroupManaging
    
    userGroupManaging --> (добавление пользователя в группы пользователей) : include
    userGroupManaging <.. (удаление пользователя из групп пользователей) : extend   
}

' adminOrg -r-  (архивировать проект)

@enduml