@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Участник организации: as member 
:Администратор организации: as adminOrg
adminOrg -l-> member

package "Управление группами пользователей" {
    (управление группами пользователей) as userGroupManaging
    adminOrg -- userGroupManaging
    
    userGroupManaging --> (добавление пользователя в группы пользователей) : include
    userGroupManaging <.. (удаление пользователя из групп пользователей) : extend   
}

package "Работа с корзиной" {
    (работа с корзиной) as trashCanManaging
    adminOrg -- trashCanManaging
    
    trashCanManaging <.. (установка частоты очистки корзины) : extend
    trashCanManaging <.. (установка максимального объема корзины) : extend
    trashCanManaging <.. (окончательное удаление элемента из корзины) : extend 
    
    note "Задаются по умолчанию" as n1
    (установка максимального объема корзины) .. n1
    (окончательное удаление элемента из корзины) .. n1
}

package "Работа с логами" {
    (работа с логами) as logManaging
    adminOrg -- logManaging
    
    logManaging <.. (просмотр логов) : extend
    logManaging <.. (удаление логов) : extend
    logManaging <.. (установка максимального объема \n логов организации) : extend
    logManaging <.. (установка максимального объема \n логов отдельного проекта) : extend
    
    note "Задаются по умолчанию" as n2
    (установка максимального объема \n логов организации) .. n2
    (установка максимального объема \n логов отдельного проекта) .. n2
}

package "Работа с резервным копированием" {
    (работа с резервным копированием) as backupManaging
    adminOrg -- backupManaging    
    
    backupManaging --> (настройка категорий для резервного копирования) : include
    backupManaging --> (настройка частоты резервного \n копирования для каждой категории) : include
    backupManaging <.. (создание резервных копий отдельных категорий) : extend
    backupManaging <.. (восстановление данных из резервных копий) : extend
}
adminOrg -r-  (архивировать проект)

@enduml