@startuml
'https://plantuml.com/use-case-diagram

left to right direction
    
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''' УЧАСТНИК БЕЗ РОЛИ

:Участник без роли: as noRole

package "Просмотр информации об организации" {
    (Просмотр информации) as watch
        noRole -- watch
        
    watch <.. (просмотр \n задач проекта): extend
    watch <.. (просмотр \n отчётов): extend
    watch <.. (просмотр \n досок проекта): extend
    watch <.. (просмотр \n колонок проекта): extend
    watch <.. (просмотр списка \nучастников организации): extend
    watch <.. (просмотр списка \nупроектов организации): extend
    watch <.. (просмотр информации \nоб организации): extend
}

@enduml