@startuml
left to right direction
    
:Участник проекта: as member
:Участник без роли: as member2

member -u-|> member2
package "Просмотр" {
    (Просмотр информации) as watch
        member2 -- watch
        
    watch <.. (просмотр \n задач проекта): extend
    watch <.. (просмотр \n отчётов): extend
    watch <.. (просмотр \n досок проекта): extend
    watch <.. (просмотр \n колонок проекта): extend
    watch <.. (просмотр списка \nучастников организации): extend
    watch <.. (просмотр списка \nупроектов организации): extend
    watch <.. (просмотр информации \nоб организации): extend
}

package "Работа с досками" {
    (работа с досками) as workOnBoards
    member -- workOnBoards
    
    workOnBoards <.. (создание доски) : extend
    workOnBoards <.. (удаление доски) : extend
    
    (редактирование доски) as boardEdit
    workOnBoards --> boardEdit : include
    
    boardEdit <.. (создание колонки) : extend
    boardEdit <.. (редактирование колонки) : extend
    boardEdit <.. (удаление колонки) : extend
    
    '(редактирование колонки) <.. (настройка максимального \n количества задач в колонке) : extend
    (редактирование колонки) <.. (создание задачи) : extend
    (редактирование колонки) <.. (редактирование задачи) : extend
    (редактирование колонки) <.. (удаление задачи) : extend
}

'package "Управление проектом" {
'    (управление проектом) as projectManaging
'    member -- projectManaging
'    
'    projectManaging <.. (редактирование информации о проекте) : extend 
'}

'package "Работа с задачами" {
'    (работа с задачами) as workWithTask
'    member -- workWithTask
'    workWithTask <.. (помещение задачи в корзину) : extend
'    workWithTask <.. (оставить комментарий к задаче) : extend
'    workWithTask --> (принять задачу) : include
'    
'    (создать задачу) as createTask
'    workWithTask --> createTask : include
'    createTask --> (задать доску размещения задачи) : include
'    createTask --> (назначить исполнителя задачи) : include
'    createTask --> (задать текст задачи) : include
'
'    (редактирование задачи) as editTask
'    workWithTask --> editTask : include
'    editTask <.. (задать доску размещения задачи) : extend
'    editTask <.. (назначить исполнителя задачи) : extend
'
'    editTask <.. (задать текст задачи) : extend
'    editTask --> (изменить статус задачи) : include
'}

':Участник организации: as member 
:Администратор организации: as adminOrg
adminOrg -u-|> member

package "Управление группами пользователей" {
    (управление группами пользователей) as userGroupManaging
    adminOrg -- userGroupManaging
    
    userGroupManaging --> (добавление пользователя в группы пользователей) : include
    userGroupManaging <.. (удаление пользователя из групп пользователей) : extend   
}

package "Управление проектами" {
    (Управление проектами) as projectsManaging
    adminOrg -- projectsManaging
    
    projectsManaging --> (создание проекта) : include
    projectsManaging <.. (удаление существующего проекта) : extend   
}

package "Управление организацией" {
    (Управление организацией) as orgManaging
    adminOrg -- orgManaging
    
    orgManaging <.. (изменения информации организации) : extend
    orgManaging <.. (добавление пользователя в организацию) : extend   
    orgManaging <.. (удаление пользователя в организацию) : extend   
}



@enduml