#%RAML 1.0
title: TFlic API
baseUri: http://localhost:8081/api
version: 1.0

# https://raml-org.github.io/playground/learn_raml.html - raml sandbox

/AuthorizationService:
    displayName: Сервис авторизации
    post:
        queryParameters:
            login:
                login: string
                required: true
            password_hash:
                password_hash: string
                required: true
        
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {"access_token": "123ad586-n6d9ee45-5f3694fr"}

            403: 
                body:
                    application/json:
                        example: |
                            {"message": "Неверные аутентификационные данные"}